version: '2'

services:
    db:
        image: mysql:5.7
        container_name: klizzy_mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: root
        ports:
            - 3336:3306
    php:
        image: klizzy/php-base:7.2
        container_name: klizzy_php
        environment:
            APACHE_DOCUMENT_ROOT: /var/www/public
        volumes:
            - symfony-docker-volume:/www:nocopy
            - symfony-docker-volume:/var/www:nocopy
        ports:
            - 8080:80
    redis:
        image: redis:6.0.8
        container_name: klizzy_redis
        ports:
            - 6379:6379
volumes:
    symfony-docker-volume: {}
