version: '2'

services:
    db:
        image: mysql:8.0.33
        container_name: symfony_docker_mysql
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: user123
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: root
        volumes:
            - symfony-docker-db_volume:/var/lib/mysql:rw
        ports:
            - "3336:3306"
    php:
        image: klizzy/php-base:8.2.1
        container_name: symfony_docker_php
        environment:
            APACHE_DOCUMENT_ROOT: /var/www/public
        volumes:
            - ./www:/var/www
        ports:
            - "8080:80"
    redis:
        image: redis:6.2.3
        container_name: symfony_docker_redis
        ports:
            - "6379:6379"
    rabbitmq:
        image: rabbitmq:3.8.16-management
        container_name: symfony_docker_rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
        ports:
            - "15672:15672"
            - "5672:5672"
    mailer:
        image: schickling/mailcatcher
        container_name: symfony_docker_mailcatcher
        restart: unless-stopped
        ports:
            - "1025"
            - "1080:1080"
volumes:
    symfony-docker-volume: {}
    symfony-docker-db_volume:
